### PR TITLE
testcases_fast.sh: Make sure we have a valid device

### LINKED ISSUE #1128: Tests fail if there is no aport for the curent device
I don't exactly know how to put it... But look at the logs.
I last worked on the device "sony-seagull", then switched branch to work on something else and run the tests. pmbootstrap remembered my choice, but it seems that it is confused by the non-existent device information.

Proposed solution: store the suggestions, run the tests and restore them. There might be another, easier way.

```
test/test_build_is_necessary.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pmb/parse/arguments.py:388: in arguments
    setattr(args, "deviceinfo", pmb.parse.deviceinfo(args))
_ _ _ _ _ _ _ _ _ ___ _ _ _ _ _ _ _ _ _ _ _ _ 

args = Namespace(action='chroot', alpine_version='edge', aports='/run/media/mayeul/DATA/postmarketos/pmbootstrap/aports', arc...rope/Paris', ui='weston', user='pmuser', verbose=False, work='/run/media/mayeul/DATA/postmarketos/pmbootstrap_workdir')
device = 'sony-seagull'

    def deviceinfo(args, device=None):
        """
        :param device: defaults to args.device
        """
        if not device:
            device = args.device
    
        if not os.path.exists(args.aports):
            logging.fatal("Aports directory is missing")
            logging.fatal("Please provide a path to the aports directory using the -p flag")
            raise RuntimeError("Aports directory missing")
    
        aport = args.aports + "/device/device-" + device
        if not os.path.exists(aport) or not os.path.exists(aport + "/deviceinfo"):
            logging.fatal("You will need to create a device-specific package")
            logging.fatal("before you can continue. Please create at least the")
            logging.fatal("following files:")
            logging.fatal(aport + "/APKBUILD")
            logging.fatal(aport + "/deviceinfo")
>           raise RuntimeError("Incomplete device information")
E           RuntimeError: Incomplete device information

pmb/parse/deviceinfo.py:43: RuntimeError
------------ Captured stderr setup ----------------
deviceinfo.py               38 CRITICAL You will need to create a device-specific package
deviceinfo.py               39 CRITICAL before you can continue. Please create at least the
deviceinfo.py               40 CRITICAL following files:
deviceinfo.py               41 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/APKBUILD
deviceinfo.py               42 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/deviceinfo
--------------------- Captured log setup -------------------
deviceinfo.py               38 CRITICAL You will need to create a device-specific package
deviceinfo.py               39 CRITICAL before you can continue. Please create at least the
deviceinfo.py               40 CRITICAL following files:
deviceinfo.py               41 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/APKBUILD
deviceinfo.py               42 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/deviceinfo
=================== 1 passed, 13 error in 2.28 seconds==================
```

### PR DESCRIPTION
**Pull request by ollieparanoid**
Fixes #1128 with a simple approach.

@MayeulC: do you want to review and test this?

### CODE REVIEW

File: test/testcases_fast.sh [hunk 1]
```diff
@@ -10,9 +10,20 @@ disabled="
 	version
 "
 
+# Make sure we have a valid device (#1128)
+cd "$(dirname "$0")/.."
+device="$(./pmbootstrap.py config device)"
+deviceinfo="$PWD/aports/device/device-$device/deviceinfo"
+if ! [ -e "./aports/device/device-$device/deviceinfo" ]; then
```
Comment (drebrez) [inline test/testcases_fast.sh]: @ollieparanoid why not using directly the `$deviceinfo` variable for the check?
```
if ! [ -e "$deviceinfo" ]; then
```

Comment (ollieparanoid) [reply test/testcases_fast.sh]: Good question, I forgot to use it there.

**Comment by ollieparanoid** [comment]
Applied the change you've suggested and merging. Thanks a lot for reviewing!
