### PR TITLE
T2M Flame updates

### LINKED ISSUE #375: [flame] Screen output flicker and inactivity
The Flame device screen is essentially inactive. A very brief flicker appears upon boot, but immediately disappears and screen turns blank. Debugging this by entering a `loop_forever` right after `show_splash` yielded the same behavior.

In `dmesg` the following (truncated) output shows that framebuffer seems to load correctly:

```
[    0.000000] Node qcom,mdss_fb_primary memblock_reserve memory 3200000-3a00000
[    0.740375] mdss_dsi_panel_init: Panel Name = ili9806c wvga video mode dsi panel
[    0.740634] mdss_dsi_panel_init:1033 Continuous splash flag enabled.
[    0.740647] mdss_dsi_panel_init:1045 Partial update disabled.
[    0.741262] mdss_register_panel: adding framebuffer device fdd00000.qcom,mdss_dsi
[    0.768116] mdp3_alloc: allocating 3280896 bytes at c3200000 (3200000 phys) for fb 0
[    0.768510] mdss_fb_register: FrameBuffer[0] 480x854 size=3280896 registered successfully!
[    0.768728] Registered led device: lcd-backlight
```

There are also some errors coming from `msm_vidc` which do not appear on a normal B2G boot, but do appear on a B2G recovery boot and the screen works there, so they can possibly be ignored (might be related to more advanced screen functions irrelevant for the framebuffer driver)
```
[    3.390004] msm_vidc: 1: Failed to read qcom,load-freq-tbl from device tree
[    3.390017] msm_vidc: 1: no elements in frequency table
[    3.390027] msm_vidc: 1: Failed to read qcom,reg-presets from device tree
[    3.390106] msm_vidc: 1: Failed to read qcom,buffer-type-tz-usage-table from device tree
[    3.390127] msm_vidc: 1: Q6 hfi device probe called
```

All sysfs parameters seem to be set correctly when diffed against the B2G params, except for one param that is set manually to match:

```bash
echo "480,1708" > /sys/devices/virtual/graphics/fb0/virtual_size
```

`fbset` output:

```bash
mode "480x854-4"
	# D: 2.252 MHz, H: 3.263 kHz, V: 3.650 Hz
	geometry 480 854 480 1708 32
	timings 444139 100 100 8 20 10 12
	accel false
	rgba 8/24,8/16,8/8,8/0
endmode
```

This workaround didn't seem to help either:

```
# cat /sys/class/graphics/fb0/modes > /sys/class/graphics/fb0/mode
# cat /sys/class/graphics/fb0/mode
U:480x854p-3
```

This also doesn't do anything:

```
# cat /dev/urandom > /dev/fb0
cat: write error: No space left on device
```

Similar symptoms to #29

### PR DESCRIPTION
**Pull request by yuvadm**
- Fixes #375 
- Removes unneccesary hacks
- Fixes bug in firmware package after rename
- Fix touchscreen

### CODE REVIEW

File: aports/device/device-t2m-flame/initfs-hook.sh [hunk 1]
```diff
@@ -1,5 +1,2 @@
 #!/bin/sh
```
Comment (drebrez) [inline aports/device/device-t2m-flame/initfs-hook.sh]: @yuvadm if the initfs-hook script is not necessary anymore, I suggest removing it completly

Comment (yuvadm) [reply aports/device/device-t2m-flame/initfs-hook.sh]: I thought I'd keep it since it might become useful again at some point, but I guess I can delete it.

**Comment by yuvadm** [comment]
@drebrez done, thanks for the review!

**Comment by yuvadm** [comment]
@ollieparanoid thanks for the feedback, done!
